config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # Defines the root path route ("/")
  root "welcome#index"

  get "checkins/:id/checked", to: "checkins#checked", as: "checked"
  patch "checkins/:id/checked", to: "checkins#checked"
  
  get "checkins/confirma", to: "checkins#confirma", as: "confirma"

  resources :checkins
  resources :criancas
  devise_for :usuarios, controllers: {
    omniauth_callbacks: 'usuarios/omniauth_callbacks',
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations'
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/checkin.rb
class Checkin < ApplicationRecord
    belongs_to :usuario, primary_key: 'uid', 
                         foreign_key: 'uid'  
end

app/models/usuario.rb
require "securerandom"

class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  before_create :gera_uuid, unless: :uid

  def gera_uuid
     self.uid = SecureRandom.uuid
     self.codigo = rand 999999 
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |usuario|
        usuario.email = auth.info.email
        usuario.password = Devise.friendly_token[0, 20]
        usuario.full_name = auth.info.name # assuming the user model has a name
        usuario.avatar_url = auth.info.image # assuming the user model has an image
        usuario.codigo = rand 999999
    end
  end

  has_many :checkins, :foreign_key => "uid", 
                   :primary_key => "uid"  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_usuario!
    #protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_crianca, only: %i[ show edit update destroy ]

  def index
    @criancas = current_usuario.checkins.all
    @crianca = Checkin.new
  end

  # POST /criancas or /criancas.json
  def create
    @crianca = Checkin.new(crianca_params.merge(uid: current_usuario.uid))

    respond_to do |format|
      if @crianca.save
        format.html { redirect_to checkins_url, notice: "Crianca was successfully created." }
        format.json { render :index, status: :created, location: @checkin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  def checked
    @checkin = Checkin.find(params[:id])
    if @checkin.update(checked: params[:checked], codigo: current_usuario.codigo)
      render json: { message: "Sucesso!"}
    else
      render json: { message: "Erro!"}
    end
  end

  def confirma    
  end

  # PATCH/PUT /criancas/1 or /criancas/1.json
  def update
    respond_to do |format|
      if @crianca.update(crianca_params)
        format.html { redirect_to checkins_url, notice: "Crianca was successfully updated." }
        format.json { render :index, status: :ok, location: @crianca }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crianca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criancas/1 or /criancas/1.json
  def destroy
    @crianca.destroy

    respond_to do |format|
      format.html { redirect_to checkins_url, notice: "Crianca was successfully destroyed." }
      format.json { head :no_content }
    end
  end  

  private

    def set_crianca
        @crianca = current_usuario.checkins.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crianca_params
      params.require(:checkin).permit(:nome, :nascimento, :observacoes, :uid, :codigo, :checked)
    end  

end

app/controllers/usuarios/confirmations_controller.rb
# frozen_string_literal: true

class Usuarios::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/usuarios/omniauth_callbacks_controller.rb
class Usuarios::OmniauthCallbacksController < Devise::OmniauthCallbacksController  

  def google_oauth2
    usuario = Usuario.from_omniauth(auth)    
    if usuario.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect usuario, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_usuario_session_path
    end
  end  

protected  

  def after_omniauth_failure_path_for(_scope)
    new_usuario_session_path
  end  

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end  

private

  def auth
    @auth ||= request.env['omniauth.auth']
  end

end

app/controllers/usuarios/passwords_controller.rb
# frozen_string_literal: true

class Usuarios::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/usuarios/registrations_controller.rb
# frozen_string_literal: true
class Usuarios::RegistrationsController < Devise::RegistrationsController  
  def update_resource(resource, params)
    if resource.provider == 'google_oauth2'
      params.delete('current_password')
      resource.password = params['password']
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
end

app/controllers/usuarios/sessions_controller.rb
class Usuarios::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(_resource_or_scope)
    new_usuario_session_path
  end  
  
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/controllers/usuarios/unlocks_controller.rb
# frozen_string_literal: true

class Usuarios::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_usuario!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
require "rqrcode"

module CheckinsHelper

    def qrcode()

        qr = RQRCode::QRCode.new(current_usuario.codigo.to_s)

    end

end

app/helpers/criancas_helper.rb
module CriancasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/checkins/_checkin.html.erb
<div id="<%= dom_id checkin %>" class="bg-white shadow px-10 py-5 border border-2 border-gray-300 rounded m-10">
  <%= form_with(model: checkin, class:"text-lg inline-block my-3 w-full") do |form| %>
    <div class="flex">
      <% if checkin.codigo.present? %>
        <div class="mt-1 mr-2">
          <%= '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            width="24px" height="24px" viewBox="0 0 426.667 426.667" style="enable-background:new 0 0 426.667 426.667;" xml:space="preserve">
          <path style="fill:#6AC259;" d="M213.333,0C95.518,0,0,95.514,0,213.333s95.518,213.333,213.333,213.333
            c117.828,0,213.333-95.514,213.333-213.333S331.157,0,213.333,0z M174.199,322.918l-93.935-93.931l31.309-31.309l62.626,62.622
            l140.894-140.898l31.309,31.309L174.199,322.918z"/>
          </svg>'.html_safe %>
        </div>
      <% else %>
        <%= form.check_box :checked, 
                          data: { id: checkin.id,
                                  action: "checkins#checked"
                                },
                          class: "mt-1 mr-2 align-middle bg-gray-50 border-gray-400 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500" %>
      <% end %>
      <div class="flex flex-col">
        <%= checkin.nome %>
        <span class="text-xs text-gray-600">
        <%= checkin.nascimento.strftime('%d/%m/%Y') %> / <%= ((Date.today - checkin.nascimento).to_i / 365.25).ceil %> anos
        </span>
      </div>
      <%= checkin.observacoes %>
    </div>
  <% end %>

  <div>
    <%= button_to "Excluir", checkin_path(checkin),
            method: :delete,
            data: { action: "checkins#delete" },
            class: "rounded-full px-4 py-1 bg-red-400 text-white" if !checkin.codigo.present? %>
  </div>
</div>

app/views/checkins/_form.html.erb
<%= form_with(model: crianca, class: "contents") do |form| %>
  <% if crianca.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(crianca.errors.count, "error") %> prohibited this crianca from being saved:</h2>

      <ul>
        <% crianca.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col sm:flex-row my-5 w-full">
    <div class="w-full sm:w-3/4 mx-2">
      <%= form.label :nome, class: 'text-xs text-gray-400' %>
      <%= form.text_field :nome, class: "block shadow rounded-md border border-gray-300 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="w-full sm:w-1/4 mx-2">
      <%= form.label :nascimento, class: 'text-xs text-gray-400' %>
      <%= form.date_field :nascimento, class: "block shadow rounded-md border border-gray-300 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  </div>

  <div class="my-5 w-full">
    <div class="mx-2">
      <%= form.label :observacoes, class: 'text-xs text-gray-400' %>
      <%= form.text_area :observacoes, rows: 4, class: "block shadow rounded-md border border-gray-300 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  </div>

  <div class="inline">
    <%= form.submit "Adicionar", class: "rounded-full py-2 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/checkins/_qrcode.html.erb
<div class="flex flex-col bg-white mb-5 w-full sm:w-1/4 justify-center items-center shadow py-5 mx-4 rounded-lg">
    <%= qrcode().as_svg(
    color: "000",
    shape_rendering: "crispEdges",
    module_size: 12,
    standalone: true,
    use_path: true
    ).html_safe %> 

    <h1 class="text-3xl font-medium"><%= current_usuario.codigo %></h1>
</div>

app/views/checkins/_usuario.html.erb
      <div class="flex flex-col items-center justify-center w-full sm:w-1/4 mb-5">

          <% if current_usuario %>
            <h2><%= current_usuario.email if current_usuario.email.present? %></h2>
            <%= image_tag(current_usuario.avatar_url, class: 'rounded-full') if current_usuario.avatar_url.present? %>
            <%= link_to "Editar Conta", edit_usuario_registration_path %>
            <%= button_to "Sair do Sistema", destroy_usuario_session_path, data: {turbo: "false"}, method: :delete %>
          <% else %>
            <%= link_to "Login", new_usuario_session_path %>
          <% end %>

      </div>

app/views/checkins/confirma.html.erb
<div class="flex flex-col w-full bg-green-500 h-screen justify-center items-center">

<%= qrcode().as_svg(
  color: "000",
  shape_rendering: "crispEdges",
  module_size: 11,
  standalone: true,
  use_path: true
).html_safe %> 

<h1 class="text-3xl font-medium"><%= current_usuario.codigo %></h1>

<p class="my-5">
  <%= link_to "Voltar", checkins_url, class: "bg-gray-300 rounded-full px-8 py-2" %>
</p>

</div>

app/views/checkins/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing crianca</h1>

  <%= render "form", crianca: @crianca %>

  <%= link_to "Show this crianca", @crianca, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to criancas", criancas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/checkins/index.html.erb
<div class="w-full bg-[#ff8b00]">

  <div class="flex justify-between mx-10 my-10">
    <div>
      <h1 class="font-bold text-4xl text-white"><span class="text-orange-800">KIDS</span> Checkin</h1>
      <p class="text-gray-600">KIDS CHECKIN, mais agilidade, mais segurança para os filhos, mais tranquilidade para os pais</p>
    </div>
  </div>

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex flex-col sm:flex-row justify-between mx-10 my-5">

      <%= render 'usuario' %>

      <div class="mx-auto w-full sm:w-3/4 mb-5 bg-white shadow p-5 rounded-lg">

        <h1 class="font-bold text-4xl">Adicionar Criança</h1>
        <%= render "form", crianca: @crianca %>

      </div>

  </div>

  <div id="criancas" data-controller="checkins" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
    <%= render @criancas %>
  </div>

  <div class="mx-10 my-5">
    <%= link_to "Código da Etiqueta", confirma_path, class: 'bg-green-600 text-white rounded-full px-5 py-3' %>
  </div>

</div>

app/views/checkins/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New crianca</h1>

  <%= render "form", crianca: @crianca %>

  <%= link_to 'Back to criancas', criancas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/checkins/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @crianca %>

    <%= link_to 'Edit this crianca', edit_crianca_path(@crianca), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this crianca', crianca_path(@crianca), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to criancas', criancas_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kidscheckin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex w-full h-screen">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kidscheckin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body>
    <section class="bg-gray-300">    
      <%= yield %>
    </section>
  </body>
</html>

app/views/welcome/_crianca.html.erb
<div class="block">
  <%= form_with(model: crianca, class:"text-lg inline-block my-3 w-72") do |form| %>
    <%= form.check_box :situacao,
                       class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500" %>
    <%= crianca.nome %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="flex w-full h-screen">
  <div class="w-1/2 p-10">
    <h1 class="font-bold text-4xl">KIDS Checkin</h1>
    <p class="text-gray-600">KIDS CHECKIN, mais agilidade, mais segurança para os filhos, mais tranquilidade para os pais</p>
  </div>
  <div class="w-1/2 bg-gray-300">
    <p>Imagem</p>
  </div>
</div>